services:
  db:
    container_name: arcadia_db
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      # - ./volumes/postgres-data/:/var/lib/postgresql/data/
      - db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - backend/.env.docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U arcadia" ]
      interval: 5s
      timeout: 5s
      retries: 5
  init_db:
    container_name: init_db
    env_file:
      - backend/.env.docker
    build:
      context: backend
      dockerfile: Dockerfile
    command: sh -c "/init_db.sh" 
    volumes:
      - ./backend/scripts/init_db.sh:/init_db.sh
    depends_on:
      db:
        condition: service_healthy
  backend:
    container_name: arcadia_backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - backend/.env.docker
      - backend/.env
    depends_on:
      db:
        condition: service_healthy
      init_db:
        condition: service_completed_successfully

  frontend:
    container_name: arcadia_frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 5173:80

volumes:
  db_data:
