services:
  db:
    container_name: arcadia_db
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      # - ./volumes/postgres-data/:/var/lib/postgresql/data/
      - db_data:/var/lib/postgresql/data/
    ports:
      - 4321:5432
    env_file:
      - backend/api/.env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arcadia"]
      interval: 5s
      timeout: 5s
      retries: 5

  init_db:
    container_name: init_db
    env_file:
      - backend/api/.env.docker
    build:
      context: ./
      dockerfile: backend/api/Dockerfile
      target: builder
    command: sh -c "/init_db.sh"
    working_dir: /app
    volumes:
      - ./backend/storage/scripts/init_db.sh:/init_db.sh
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis
    container_name: arcadia_redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    env_file:
      - backend/api/.env.docker
      - backend/api/.env
    command: redis-server --requirepass ${REDIS_PASSWORD}

  backend:
    container_name: arcadia_api
    build:
      context: ./
      dockerfile: backend/api/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - backend/api/.env.docker
    develop:
      watch:
        - path: ./backend/api
          action: rebuild
        - path: ./backend/api
          action: restart
          include:
            - .env.docker

  frontend:
    container_name: arcadia_frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 5173:80
    env_file:
      - frontend/.env.docker
    develop:
      watch:
        - path: ./frontend/dist
          action: sync
          target: /usr/share/nginx/html
        - path: ./frontend/docker/nginx.conf
          action: sync+restart
          target: /etc/nginx/conf.d/default.conf

volumes:
  db_data:
  redis_data:
